import SessionProvider from "@/components/providers/session-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import Navbar from "@/components/navbar";
import { cn } from "@/lib/utils";
import UserLocationProvider from "@/components/providers/user-location-provider";
import SelectedBusinessProvider from "@/components/providers/selected-business-provider";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body
        className={cn("bg-white min-h-screen min-w-full", raleway.className)}
      >
        <SessionProvider>
          <UserLocationProvider>
            <SelectedBusinessProvider>
              <main>
                <Navbar />
                {children}
              </main>
            </SelectedBusinessProvider>
          </UserLocationProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
