import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/components/providers";
import { LeftSidebar, RightSidebar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <div className="w-full h-full flex justify-center items-center relative bg-black">
            <div className="max-w-screen-2xl w-full h-full flex relative">
              {/* left sidebar`` */}
              <section className="flex-1">
                <LeftSidebar className="hidden lg:block" />
              </section>

              <main className="w-full lg:w-[48%]">{children}</main>

              {/* right sidebar */}
              <section className="lg:w-[30%]">
                <RightSidebar className="hidden lg:block" />
              </section>
            </div>
          </div>

          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
